services:
  keycloak:
    image: keycloak/keycloak:26.3
    container_name: keycloak
    ports:
      - ${KEYCLOAK_PORT:-8081}:8080
    environment:
      - "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=admin"
      - "KEYCLOAK_IMPORT=/opt/keycloak/data/import"
      - "KC_CACHE=local"
      - "KC_DB=postgres"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"
      - "KC_DB_URL_PORT=5432"
      - "KC_DB_URL_DATABASE=keycloak"
      - "KC_DB_URL_HOST=postgres"
      - "KC_HTTP_ENABLED=true"
      - "KC_HOSTNAME=http://localhost:8081"
    volumes:
      - keycloak:/opt/keycloak/data
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
    command:
      - "start-dev"
      - "--import-realm"
    depends_on:
      - postgres
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MP_DATA_FILE=/data/mailpit.db
      - TZ=Europe/London
    volumes:
      - mailpit:/data
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    command:
      - server
      - /data
      - --address
      - :9000
      - --console-address
      - :9001

  minio-init:
    image: quay.io/minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 admin adminadmin) do sleep 1; done &&
      /usr/bin/mc mb --ignore-existing local/demo &&
      exit 0
      "
  postgres:
    image: postgres:17.5
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "TZ=UTC"
    tmpfs:
      - /tmp/postgresql/data
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - postgres
      - -c
      - max_connections=10
      - -c
      - shared_buffers=1GB
      - -c
      - fsync=off
      - -c
      - full_page_writes=off
  # flyway:
  #   image: flyway/flyway:10
  #   container_name: flyway_migrations
  #   depends_on:
  #     - postgres
  #   command:
  #     - -url=jdbc:postgresql://postgres:5432/postgres
  #     - -user=postgres
  #     - -password=postgres
  #     - -connectRetries=10
  #     - migrate
  #   volumes:
  #     - ../../src/main/resources/db/migration:/flyway/sql
  #   environment:
  #     FLYWAY_PLACEHOLDERS_ENV: postgres

volumes:
  keycloak:
    driver: local
    driver_opts:
      type: none
      device: "/opt/demo-com/keycloak"
      o: bind
  mailpit:
    driver: local
    driver_opts:
      type: none
      device: "/opt/demo-com/mailpit"
      o: bind
  minio:
    driver: local
    driver_opts:
      type: none
      device: "/opt/demo-com/minio"
      o: bind
  postgresql: