# =================================
# SPRING CUSTOMIZATION
# =================================
spring:
  application:
    name: Demo App
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
      cache:
        period: 0
        cachecontrol:
          no-cache: true
          no-store: true
          must-revalidate: true
  lifecycle:
    timeout-per-shutdown-phase: 15s # TODO verify this works well with current infra
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo
            client-secret: demo
            scope: openid,profile,email
            provider: keycloak
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/demo-iam
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB
  devtools:
    add-properties: true
    restart:
      enabled: true # does not work with Jetty
# =================================
# CORS
# =================================
management:
  endpoints:
    web:
      base-path: /
      cors:
        allowed-origin-patterns: "*"
        allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
        allowed-headers: "*"
# =================================
# LOGGING
# =================================
logging:
  level:
    root: INFO
    web: INFO
  file:
    name: /opt/demo-com/spring/app.log
    max-size: 10MB
    total-size-cap: 100MB
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
# =================================
# GENERAL SERVER TWEAKS
# =================================
server:
  port: 8443
  shutdown: immediate # FIXME shudown varies from enviroment
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: demo-app
  http2:
    enabled: true
# =================================
# Providers configuration
# =================================
minio:
  url: http://localhost:9000
  access:
    name: admin
    secret: adminadmin
  bucket:
    name: demo

# =================================
# Demo App custom variables
# =================================
app:
  url: https://localhost:8443

demo:
  vite:
    manifest-location: classpath:static/.vite/manifest.json